# Generated by Django 2.0.8 on 2018-09-16 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 16, 15, 49, 7, 364853, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
