# Generated by Django 2.1.1 on 2018-09-16 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180916_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 19, 24, 18, 935788, tzinfo=utc), validators=[posts.models.time_stamps]),
        ),
    ]
