# Generated by Django 2.1.1 on 2018-09-16 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180916_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='last_update',
            field=models.DateTimeField(validators=[posts.models.time_stamps], verbose_name=datetime.datetime(2018, 9, 16, 19, 42, 53, 737389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
