# Generated by Django 2.1.1 on 2018-09-17 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180916_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='last_update',
            field=models.DateTimeField(validators=[posts.models.time_stamps], verbose_name=datetime.datetime(2018, 9, 17, 5, 17, 27, 813484, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='likes',
            name='post_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
    ]
